quarkus.config-tracking.enabled=true
# Loggeo
quarkus.log.category."ciudadano.consciente".level=DEBUG

# Seleccionamos otro puerto que no sea el por defecto
quarkus.http.port=5909

#cors
quarkus.http.cors=true
quarkus.http.cors.origins=*

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=false

# Remover el banner de Quarkus
quarkus.banner.enabled=false

# front externo
#quarkus.http.cors.origins=http://localhost:5273

# Nombre de la imagen a construir (por defecto nombre de la app - set in BuildTime)
# quarkus.container-image.name=ciuco

# VARIABLES QUE SE PUEDEN DEFINIR DESDE EL COMPOSE
# Acceder al fileSystem
# Thumbnail images
#file.system.images.version.thumbnail=/home/saimon/Projects/CiudadanoConsciente/resources/images/activity-type-version/thumbnail
# Content images
#file.system.images.content=/home/saimon/Projects/CiudadanoConsciente/resources/images/content

# Setear el máximo file size de una imagen
#image.max.mb.size=5

# APIs GITHUB
#quarkus.rest-client.api-github-content.url=https://raw.githubusercontent.com/

# Para visualizar logs de la api consumida
quarkus.rest-client.logging.scope=request-response
quarkus.rest-client.logging.body-limit=500
quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG
