# Loggeo
quarkus.log.category."ciudadano.consciente".level=DEBUG

#cors
quarkus.http.cors=true
quarkus.http.cors.origins=*

# Seleccionamos otro puerto que no sea el por defecto
quarkus.http.port=5909

# Solo necesario si hay más BD conectadas
quarkus.datasource.db-kind=postgresql

# Determinar user, contraseña, url y conexiones
quarkus.datasource.username=saimon
quarkus.datasource.password=chipaParaguaya
# Container
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:3707/ciudadano_consciente
# Local
# quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/ciudadano_consciente
quarkus.datasource.jdbc.max-size=16

# hibernate
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=false

# keycloak
quarkus.oidc.auth-server-url=http://192.168.1.17:3704/realms/Ciudadano
quarkus.oidc.client-id=api-ciudadano-consciente
quarkus.oidc.credentials.secret=127iCwfSvfEsiLmlA0NKNNLzvrKLlRy0
quarkus.oidc.authentication.user-info-required=true

# front externo
#quarkus.http.cors.origins=http://localhost:5273
