# Loggeo
quarkus.log.category."ciudadano.consciente".level=DEBUG
#quarkus.log.category."ciudadano.consciente".level=TRACE
# Definir timezone ya que no lo persistimos en DB pero podemos formatear la fecha (al escribir)
quarkus.hibernate-orm.jdbc.timezone=America/Argentina/Ushuaia
# Al leerlo lo normalizamos a la zona horaria de la propiedad (al mapear, leer)
quarkus.hibernate-orm.mapping.timezone.default-storage=normalize

# Persistir loggeo en archivo
quarkus.log.file.enable=true
quarkus.log.file.path=${LOGS_DIRECTORY}/${quarkus.application.name}
#quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss,SSS\ %h %N[%i] %-5p [%c{3.\}] (%t) %s%e%n}
quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %h [%t] %-5p [%c{3}] (%t) %s%e%n
quarkus.log.file.rotation.file-suffix=.yyyyMMdd
quarkus.log.file.rotation.rotate-on-boot=true

#cors
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PATCH,DELETE,OPTIONS
quarkus.http.cors.access-control-allow-credentials=true
quarkus.http.cors.exposed-headers=Authorization,Content-Type

# Seleccionamos otro puerto que no sea el por defecto
quarkus.http.port=5909
# Para que puedan acceder desde la misma red con host:puerto de la API
# OMITIR EN COMPOSE
quarkus.http.host=0.0.0.0

    # Thumbnail images
file.system.images.version.thumbnail=${THUMBNAIL_DIRECTORY}
    # Content images
file.system.images.content=${CONTENT_IMAGES_DIRECTORY}

# Setear el m�ximo file size de una imagen
image.max.mb.size=5

# Solo necesario si hay m�s BD conectadas
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${USERNAME_DB}
quarkus.datasource.password=${PASSWORD_DB}
quarkus.datasource.jdbc.url=${JDBC_URL}
quarkus.datasource.jdbc.max-size=16

# hibernate
quarkus.hibernate-orm.database.generation=none
#quarkus.hibernate-orm.log.sql=true

# Remover el banner de Quarkus
quarkus.banner.enabled=false

# keycloak OIDC
realm=${REALM}
quarkus.oidc.auth-server-url=${OIDC_AUTH_SERVER_URL}
quarkus.oidc.client-id=${OIDC_CLIENT_ID}
quarkus.oidc.credentials.secret=${OIDC_SECRET}
# Si esta variable booleana se pone en el .env, no se pasa el token a swagger ui
quarkus.oidc.authentication.user-info-required=true


# Cuenta de servicio del Cliente OIDC
quarkus.oidc-client.auth-server-url=${OIDC_AUTH_SERVER_URL}
quarkus.oidc-client.client-id=${OIDC_CLIENT_ID}
quarkus.oidc-client.credentials.secret=${OIDC_SECRET}
quarkus.oidc-client.grant.type=client

# APIs EXTERNAS
#quarkus.rest-client.api-github-content.url=https://raw.githubusercontent.com/

# Si consumo como rest Client la API-rest de admin de quarkus que hice, debo pasarle un token
quarkus.rest-client.api-keycloak.url=${REST_CLIENT_API_ADMIN_KEYCLOAK_URL}
#quarkus.rest-client.desa-api-keycloak.url=${DESA_REST_CLIENT_API_ADMIN_KEYCLOAK_URL}
#quarkus.rest-client.desa-api-keycloak.url=${REST_CLIENT_API_ADMIN_KEYCLOAK_URL}

# Para visualizar logs de la api consumida
quarkus.rest-client.logging.scope=request-response
quarkus.rest-client.logging.body-limit=500
quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG



#quarkus.log.level=ALL
