# Loggeo
quarkus.log.category."ciudadano.consciente".level=DEBUG

#cors
quarkus.http.cors=true
quarkus.http.cors.origins=*

# Solo necesario si hay más BD conectadas
quarkus.datasource.db-kind=postgresql

# Determinar user, contraseña, url y conexiones
quarkus.datasource.username=saimon
quarkus.datasource.password=chipaParaguaya

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/ciudadano_consciente
quarkus.datasource.jdbc.max-size=16

# hibernate
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=false

# front externo
#quarkus.http.cors.origins=http://localhost:5273
