# Nivel de Loggeo del paquete 'keycloak'
quarkus.log.category."keycloak".level=DEBUG

# Persistir loggeo en archivo
#quarkus.log.file.enable=true
#quarkus.log.file.path=logs/${quarkus.application.name}
#quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss,SSS\ %h %N[%i] %-5p [%c{3.\}] (%t) %s%e%n}
#quarkus.log.file.rotation.file-suffix=.yyyyMMdd
#quarkus.log.file.rotation.rotate-on-boot=true

#cors
quarkus.http.cors=true
quarkus.http.cors.origins=*

# Seleccionamos otro puerto que no sea el por defecto
quarkus.http.port=3702

# Remover el banner de Quarkus
quarkus.banner.enabled=false

# Quarkus based Keycloak distribution (CONEXIÓN AL SERVIDOR DE KEYCLOAK COMO  REST ADMIN)
quarkus.keycloak.admin-client.enabled=true
quarkus.keycloak.admin-client.server-url=http://localhost:3703
quarkus.keycloak.admin-client.realm=Ciudadano
quarkus.keycloak.admin-client.client-id=api-keycloak-admin
quarkus.keycloak.admin-client.client-secret=xvrUsuB8c3nk1gopr5FGwRbDqMd7GkTn
#quarkus.keycloak.admin-client.username= # remove default username
#quarkus.keycloak.admin-client.password= # remove default password
quarkus.keycloak.admin-client.grant-type=CLIENT_CREDENTIALS

# keycloak OIDC (COMO CLIENTE ANTE EL CUAL PRESENTAR CREDENCIALES)
quarkus.oidc.auth-server-url=http://localhost:3703/realms/Ciudadano
quarkus.oidc.client-id=api-keycloak-admin
quarkus.oidc.credentials.secret=xvrUsuB8c3nk1gopr5FGwRbDqMd7GkTn

# Para visualizar logs de la api consumida
quarkus.rest-client.logging.scope=request-response
quarkus.rest-client.logging.body-limit=500
quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG