version: '3.1'

services:

  db:
    image: postgres:16
    container_name: postgres
    deploy:
      resources:
        limits:
          memory: 50M # Limita a 50MB máximo de RAM
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - 3707:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d  # Montar los scripts de inicialización (solo sirve si no hay nada en el directorio de datos mencionados arriba).
    hostname:
      "postgres"

volumes:
  pg_data:


