services:

  ciuco_db:
    image: postgres:16
    container_name: ciuco_db
    deploy:
      resources:
        limits:
          memory: 100M # Limita a 100MB máximo de RAM
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PASSWORD_DB} # Si se explicita acá, no lo ponemos en el script
      POSTGRES_USER: ${USERNAME_DB} # Si se explicita acá, no lo ponemos en el script
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 3700:5432
    volumes:
      - ciuco_data:/var/lib/postgresql/data
      - ./init_CIUCO.sql:/docker-entrypoint-initdb.d/init.sql  # Montar los scripts de inicialización (solo sirve si no hay nada en el directorio de datos mencionados arriba).
    networks: 
      - citizen_network
    hostname: ciuco_db # El nombre con el que aparace en la red principal
 
  kc_db:
    image: postgres:16
    container_name: kc_db
    deploy:
      resources:
        limits:
          memory: 100M # Limita a 100MB máximo de RAM
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PASSWORD_DB_KC} 
      POSTGRES_USER: ${USERNAME_DB_KC}
      POSTGRES_DB: ${KEYCLOAK_DB}
    ports:
      - 3701:5432
    volumes:
      - kc_data:/var/lib/postgresql/data
      - ./init_KC.sql:/docker-entrypoint-initdb.d/init.sql  # Montar los scripts de inicialización (solo sirve si no hay nada en el directorio de datos mencionados arriba).
    networks: 
      - citizen_network
    hostname: kc_db # El nombre con el que aparace en la red principal

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    deploy:
      resources:
        limits:
          memory: 500M
    restart: always
    ports:
      - 3703:8080
    environment:
      - TZ=America/Argentina/Ushuaia # Para la JVM
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD} # esta clave solo se setea si no existe ninguna, debemos cambiar esta clave
      # DEPRECATED - KC_HOSTNAME_URL=http://localhost:3704 # Para poder acceder desde afuera de la red del contenedor
      # DEPRECATED - KC_HOSTNAME_ADMIN_URL=http://localhost:3704 # Esta url debe poder ser accesible por fuera de la red del contenedor (si la mapeamos internamente, desde fuera no saben el nombre del servicio.)
      - KC_HOSTNAME_STRICT=false
        #- KC_HOSTNAME_STRICT_BACKCHANNEL=true # DEPRECTED
      - KC_HTTP_ENABLED=true # Migrado desde KC23 -- KC_PROXY=edge # permite HTTP (https://www.keycloak.org/docs/25.0.2/upgrading/#deprecated-proxy-option)
      - KC_PROXY_HEADERS=xforwarded
      - KC_PROXY_PROTOCOL_ENABLED=true
      - PROXY_ADDRESS_FORWARDING=true
        #- KC_PROXY=edge # DEPRECATED
        #- KEYCLOAK_COOKIE_SECURE=false
      - KC_DB_URL=${KEYCLOAK_DB_URL}
      - KC_DB=postgres
      - KC_DB_SCHEMA=${KEYCLOAK_DB_SCHEMA}
      - KC_DB_USERNAME=${USERNAME_DB}
      - KC_DB_PASSWORD=${PASSWORD_DB}
      - KC_FEATURES=docker,admin-fine-grained-authz,organization
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    command: start --log="console,file" 
    volumes:
       - logs:/opt/keycloak/data/log/ # mapeamos carpeta de logs para que se guarden fuera del contenedor
    networks: 
      - citizen_network
    hostname: keycloak
  
  kc-admin-admin:
    image: csparadiso/api-rest-admin-keycloak:1.0.0
    container_name: kc_admin_api
    deploy:
      resources:
        limits:
          memory: 500M
    restart: always
    ports:
      - 3702:3702
    environment:      
      - QUARKUS_KEYCLOAK_ADMIN_CLIENT_ENABLED=true
      - QUARKUS_KEYCLOAK_ADMIN_CLIENT_SERVER_URL=${REST_CLIENT_API_ADMIN_KEYCLOAK_URL}
      - QUARKUS_KEYCLOAK_ADMIN_CLIENT_REALM=${REST_CLIENT_API_ADMIN_KEYCLOAK_REALM}
      - QUARKUS_KEYCLOAK_ADMIN_CLIENT_CLIENT_ID=${REST_CLIENT_API_ADMIN_KEYCLOAK_CLIENT_ID}
      - QUARKUS_KEYCLOAK_ADMIN_CLIENT_CLIENT_SECRET=${REST_CLIENT_API_ADMIN_KEYCLOAK_SECRET}
      - QUARKUS_KEYCLOAK_ADMIN_CLIENT_GRANT_TYPE=CLIENT_CREDENTIALS
      - QUARKUS_OIDC_AUTH_SERVER_URL=${QUARKUS_OIDC_AUTH_SERVER_URL}
      - QUARKUS_OIDC_CLIENT_ID=${QUARKUS_OIDC_CLIENT_ID}
      - QUARKUS_OIDC_CREDENTIALS_SECRET=${QUARKUS_OIDC_CREDENTIALS_SECRET}
    networks: 
      - citizen_network
    hostname: kc_admin_api

  ciuco_api:
    image: csparadiso/api-ciudadano-consciente:1.2.0
    container_name: ciuco_api
    deploy:
      resources:
        limits:
          memory: 500M
    restart: always
    ports:
      - 3705:5909
    environment:
      - QUARKUS_HTTP_CORS_ENABLED=true
      - QUARKUS_HTTP_CORS_ORIGINS=*
      - QUARKUS_HTTP_CORS_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - QUARKUS_HTTP_CORS_HEADERS=Authorization,Content-Type
      - QUARKUS_HTTP_CORS_EXPOSED_HEADERS=Content-Type
      - QUARKUS_HTTP_CORS_ALLOW_CREDENTIALS=true
      - TZ=America/Argentina/Ushuaia # Para la JVM
      - QUARKUS_HIBERNATE_ORM_JDBC_TIMEZONE=America/Argentina/Ushuaia # Para el ORM
      - QUARKUS_HIBERNATE_ORM_MAPPING_TIMEZONE_DEFAULT_STORAGE=normalize # Toma el timezone de la JDBC al mapear
      - QUARKUS_DATASOURCE_USERNAME=${USERNAME_DB}
      - QUARKUS_DATASOURCE_PASSWORD=${PASSWORD_DB} 
      - QUARKUS_DATASOURCE_JDBC_URL=${JDBC_URL}
      - QUARKUS_DATASOURCE_JDBC_MAX_SIZE=16
        #- QUARKUS_OIDC_AUTH_SERVER_URL=http://keycloak:3703/realms/Ciudadano/ # Acceder desde el servicio interno # NO LLEGA A http://localhost:3704/realms/Ciudadano PERO SI A keycloak:8080
        # ROMPE LA APP LA RUTA - QUARKUS_OIDC_AUTH_SERVER_URL=http://keycloak:8080/realms/Ciudadano # Acceder desde el servicio interno
      - QUARKUS_OIDC_AUTH_SERVER_URL=${OIDC_AUTH_SERVER_URL} # localhost:3703
        #- QUARKUS_OIDC_AUTH_SERVER_URL=http://keycloak:8080/auth/realms/Ciudadano # localhost:3703
      - QUARKUS_OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - QUARKUS_OIDC_CREDENTIALS_SECRET=${OIDC_SECRET}
      - QUARKUS_OIDC_AUTHENTICATION_USER_INFO_REQUIRE=true
      - FILE_SYSTEM_IMAGES_VERSION_THUMBNAIL=/var/tmp/CiudadanoConsciente/resources/images/activity-type-version/thumbnail
      - FILE_SYSTEM_IMAGES_CONTENT=/var/tmp/CiudadanoConsciente/resources/images/content
      - IMAGE_MAX_MB_SIZE=5
      - QUARKUS_LOG_FILE_ROTATION_FILE_SUFFIX=.yyyyMMdd
       # Cuenta de servicio del Cliente OIDC
      - REALM=${REALM}
      - QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL=${OIDC_AUTH_SERVER_URL}
        #- QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL=http://keycloak:8080/auth/realms/Ciudadano
      - QUARKUS_OIDC_CLIENT_CLIENT_ID=${OIDC_CLIENT_ID}
      - QUARKUS_OIDC_CLIENT_CREDENTIALS_SECRET=${OIDC_SECRET}
      - QUARKUS_OIDC_CLIENT_GRANT_TYPE=client
      - QUARKUS_REST_CLIENT_API_KEYCLOAK_URL=${REST_CLIENT_API_ADMIN_KEYCLOAK_URL}
    volumes: # volumeName:containerFileSystem
      - logs:/home/jboss/logs
      - thumbnail_images:/var/tmp/CiudadanoConsciente/resources/images/activity-type-version/thumbnail
      - content_images:/var/tmp/CiudadanoConsciente/resources/images/content
    networks: 
      - citizen_network
    hostname: ciuco_api
    
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://keycloak:8080"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ciuco_data:
  kc_data:
  logs: # Esto permite que Docker se encargue del volumen (permisos) pero con mapeo manual
    driver: local
    driver_opts:
      type: none
      device: ${LOGS_DIRECTORY}  # Local path to use for the volume
      o: bind
  thumbnail_images: 
    driver: local
    driver_opts:
      type: none
      device: ${THUMBNAIL_DIRECTORY} # Local path to use for the volume
      o: bind
  content_images:
    driver: local
    driver_opts:
      type: none
      device: ${CONTENT_IMAGES_DIRECTORY} # Local path to use for the volume
      o: bind

networks:
  citizen_network:
    driver: bridge
