version: '3.1'

services:

  db:
    image: postgres:16
    container_name: postgres
    deploy:
      resources:
        limits:
          memory: 50M # Limita a 50MB máximo de RAM
    restart: always
    environment:
      POSTGRES_PASSWORD: chipaParaguaya
    ports:
      - 3700:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d  # Montar los scripts de inicialización (solo sirve si no hay nada en el directorio de datos mencionados arriba).
        #networks:
        #- citizen # La red principal a la que se conecta
    networks:
      - citizen
    hostname:
      "postgres" # El nombre con el que aparace en la red principal

networks:
  citizen: 
    name: citizen
    external: true

volumes:
  pg_data:
