version: '3.1'

services:

  adminer:
    image: adminer:4.8.1-standalone
    container_name: adminer
    deploy:
      resources:
        limits:
          memory: 50M
    restart: always
    ports:
      - 3706:8080
    networks:
    - citizen # La red principal a la que se conecta
    hostname:
      "adminer" # El nombre con el que aparece en la redi

networks:
  citizen:
    name: citizen
    external: true
