version: "3.6"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    network_mode: bridge
    restart: always
    ports:
      - 3704:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin # esta clave solo se setea si no existe ninguna, debemos cambiar esta clave
      - KC_HOSTNAME_URL=http://192.168.1.17:3704
      - KC_HOSTNAME_ADMIN_URL=http://192.168.1.17:3704
      - KC_HOSTNAME_STRICT_BACKCHANNEL=true
      - KC_PROXY=edge # permite HTTP
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://192.168.1.17:5432/keycloak
      - KC_DB_SCHEMA=keycloak
      - KC_DB_USERNAME=saimon
      - KC_DB_PASSWORD=chipaParaguaya
      - KC_FEATURES=docker,admin-fine-grained-authz
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    command: start --log="console,file" 
    volumes:
       - ./logs:/opt/keycloak/data/log/ # mapeamos carpeta de logs para que se guarden fuera del contenedor

