version: '3.1'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak
    deploy:
      resources:
        limits:
          memory: 500M
    restart: always
    ports:
      - 3704:8080
    environment:
      - TZ=America/Argentina/Ushuaia # Para la JVM
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=chipaParaguaya # esta clave solo se setea si no existe ninguna, debemos cambiar esta clave
      - KC_HOSTNAME_URL=http://localhost:3704 # Para poder acceder desde afuera de la red del contenedor
      #- KC_HOSTNAME_URL=http://192.168.43.216:3704 # Esta url debe poder ser accesible por fuera de la red del contenedor (si la mapeamos internamente, desde fuera no saben el nombre del servicio.) 
      - KC_HOSTNAME_ADMIN_URL=http://localhost:3704 # Esta url debe poder ser accesible por fuera de la red del contenedor (si la mapeamos internamente, desde fuera no saben el nombre del servicio.)
      - KC_HOSTNAME_STRICT_BACKCHANNEL=true
      - KC_PROXY=edge # permite HTTP
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_SCHEMA=keycloak
      - KC_DB_USERNAME=saimon
      - KC_DB_PASSWORD=chipaParaguaya
      - KC_FEATURES=docker,admin-fine-grained-authz
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    command: start --log="console,file" 
    volumes:
       - ./logs:/opt/keycloak/data/log/ # mapeamos carpeta de logs para que se guarden fuera del contenedor
    networks:
      - citizen
    hostname:
      "keycloak"

networks:
  citizen:
    external: true
